apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: secure-devops
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: app
      image: docker.io/library/nginx:1.25.2@sha256:87198d89e5271a3378b2778da5a339903b4142f10d297a7a1ecb183fb0b1a03a
      securityContext:
        runAsUser: 10001
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop:
            - ALL
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 5
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 15
        periodSeconds: 10
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "256Mi"
      imagePullPolicy: Always
